document.write( Math.trunc( 4.1 ) + "<br>" );
document.write( Math.trunc( -4.1 ) + "<br>" );
document.write( Math.sign( 0 ) + "<br>" );
document.write( Math.sign( -55 ) + "<br>" );
document.write( Math.sign( 55 ) + "<br>" );
document.write( Math.sign( -3.5 ) + "<br>" );
document.write( Math.cbrt( 5 ) + "<br>" );
document.write( Math.fround( 1.337 ) + "<br>" );
document.write( Math.fround( -1.337 ) + "<br>" );
document.write( Math.fround( 0 ) + "<br>" );
document.write( Math.hypot( 3, 4 ) + "<br>" );
