define(function () {

    return [{
        "deptName": "全公司",
        "displayOrder": 0,
        "id": -1,
        "parentId": -1,
        "userList": [{
            "deleted": "N",
            "deptId": -1,
            "displayName": "jjj3",
            "gender": "男",
            "id": 100000041804,
            "online": false,
            "posName": "业务经理",
            "staffNo": "sddsdsds"
        }, {
            "deleted": "N",
            "deptId": -1,
            "displayName": "jjj1",
            "gender": "男",
            "id": 100000044488,
            "online": false,
            "posName": "区域经理",
            "staffNo": "323432432"
        }, {
            "deleted": "N",
            "deptId": -1,
            "displayName": "jjj2",
            "gender": "男",
            "id": 100000044489,
            "online": false,
            "posName": "区域经理",
            "staffNo": "sdfsdfds"
        }, {
            "deleted": "N",
            "deptId": -1,
            "displayName": "laoqi",
            "gender": "男",
            "id": 100000028783,
            "online": false,
            "posName": "区域副经理",
            "staffNo": "232"
        }, {
            "deleted": "N",
            "deptId": -1,
            "displayName": "laoqi",
            "gender": "男",
            "id": 100000028782,
            "online": false,
            "posName": "区域副经理",
            "staffNo": "999"
        }],
        "valid": true
    }, {
        "deptName": "a2",
        "displayOrder": 0,
        "id": 100000133003,
        "parentId": -1,
        "userList": [{
            "deleted": "N",
            "deptId": -1,
            "displayName": "ewr",
            "gender": "男",
            "id": 100000042885,
            "online": false,
            "staffNo": "235"
        }],
        "valid": true
    }, {
        "deptName": "d",
        "displayOrder": 0,
        "id": 100000053001,
        "parentId": -1,
        "userList": [{
            "deleted": "N",
            "deptId": -1,
            "displayName": "你好123",
            "gender": "男",
            "id": 100000023096,
            "mobile": "34543",
            "online": false,
            "phone": "",
            "photoUrl": "userPhoto/11000343/100000023096/888d130f-ed4d-4c9c-a774-37ba3914c012_1438759575563.jpg",
            "posName": "业务经理",
            "staffNo": "98079875"
        }, {
            "deleted": "N",
            "deptId": -1,
            "displayName": "李木梓",
            "gender": "男",
            "id": 100000023085,
            "online": false,
            "photoUrl": "userPhoto/11000343/100000023085/54eebb0b-d943-4a0c-b542-84940cdae12a.jpg",
            "posName": "业务经理",
            "staffNo": "12345659"
        }],
        "valid": true
    }, {
        "deptName": "往事如风",
        "displayOrder": 0,
        "id": 100000035704,
        "parentId": -1,
        "userList": [{
            "deleted": "N",
            "deptId": -1,
            "displayName": "测试账号2",
            "gender": "男",
            "id": 100000023082,
            "mobile": "",
            "online": false,
            "phone": "",
            "photoUrl": "userPhoto/11000343/100000023082/8956bb73-dee0-4098-9286-f59a53fe1154_1432634304813.jpg",
            "posName": "技术总监",
            "staffNo": "0755"
        }, {
            "deleted": "N",
            "deptId": -1,
            "displayName": "010-A",
            "gender": "男",
            "id": 100000024983,
            "mobile": "",
            "online": false,
            "phone": "",
            "staffNo": "010"
        }, {
            "deleted": "N",
            "deptId": -1,
            "displayName": "小黑",
            "gender": "男",
            "id": 100000049984,
            "online": false,
            "staffNo": "43543543"
        }, {
            "deleted": "N",
            "deptId": -1,
            "displayName": "zhangsan",
            "gender": "男",
            "id": 100000023092,
            "online": false,
            "posName": "高级工程师",
            "staffNo": "564534"
        }],
        "valid": true
    }, {
        "deptName": "aaa",
        "displayOrder": 0,
        "id": 100000035703,
        "parentId": -1,
        "userList": [{
            "deleted": "N",
            "deptId": -1,
            "displayName": "laowu",
            "gender": "男",
            "id": 100000028781,
            "online": false,
            "posName": "区域经理",
            "staffNo": "12346"
        }],
        "valid": true
    }, {
        "deptName": "dennis小组",
        "displayOrder": 0,
        "id": 100000222101,
        "parentId": -1,
        "userList": [{
            "deleted": "N",
            "deptId": -1,
            "displayName": "110",
            "gender": "男",
            "id": 100000054606,
            "online": false,
            "posName": "区域副经理",
            "staffNo": "110"
        }, {
            "deleted": "N",
            "deptId": -1,
            "displayName": "119",
            "gender": "男",
            "id": 100000054607,
            "online": false,
            "posName": "业务经理",
            "staffNo": "119"
        }, {
            "deleted": "N",
            "deptId": -1,
            "displayName": "我(( - 是 1 20",
            "gender": "男",
            "id": 100000056085,
            "mobile": "",
            "online": false,
            "phone": "",
            "posName": "业务助理",
            "staffNo": "3232423"
        }],
        "valid": true
    }]
});
